#Alfresco Extractor Configuration
#Thu Feb 05 12:03:20 CET 2026
cmis.user=admin
cmis.maxItems=2
cmis.url=http\://172.22.5.118\:8080/alfresco/api/-default-/public/cmis/versions/1.1/atom
cmis.lastNodeId=c47a0407-cf66-4619-8316-a487421580af
cmis.password=admin
